import datetime
datetimenow = datetime.datetime.now()

ProName = str(input("Enter the Product Name: "))
ProdSr = int(input("Enter the Product Serial Name: "))
PoRew = float(input("Positive review : "))
NeRew = float(input("Negative review : "))
totalRew = (PoRew + NeRew)
reviewscore = "{:.2f}".format(PoRew/totalRew)
print("="*30)
print("Product Name: ",ProName)
print("Product Serial Number: ",ProdSr)
print("Date> ",datetimenow.strftime("%x"))
print("Time> ",datetimenow.strftime("%X"))
print("="*30)
print("-"*30)
print("Total Number of Positive Review is:",PoRew)
print("Total Number of Negative Review is:",NeRew)
print("Review Score is:",reviewscore)
print("bye!")
print("-"*30)
